### ISSUE TITLE
Java 11 - StageHelper.getStage() not exits

### ISSUE THREAD

**Issue by JhonnySalles** [Dansoftowner/FXTaskbarProgressBar#1]
Good morning, you made a great project to use the progress of windows.
Thank you.

I would like to report a bug in the Java 11 version, the StageHelper class does not exit getStage() function, has been removed.

You can work around this using the static classes, because the use of the windows class is implemented.

TaskbarProgressbar.showIndeterminateProgress (0);

**Comment by Dansoftowner** [comment]
Hi!

I'm so glad to hear that my library is useful to you.

You made me motivated to work on this project, so I will
make the API cleaner and I'll create a new branch for 
java 11 too 🙂.

I will let you know  when java 11 support is available!
Thanks for your comment!

**Comment by JhonnySalles** [comment]
Thanks.

It is really very useful to be able to use the windows progress bar, avoid having to open the program to know progress.

This is a feature that should be native. I try my best to use what windows has to offer, but many things are missing in javafx. I wanted to use the popup on the windows taskbar, it is something that is easily accessed programs in c and delphi, but it is quite expensive in java. I understand that it is due to its limitation and its multiplatform support.


But I am very grateful for this project, I do not know Java programming so deeply, and it took me a long time to find your project.

I look forward to new updates.

**Comment by Dansoftowner** [comment]
Yes, it was very uncomfortable for me that javaFX doesn't have these features by default 
too. JavaFX is an awesome UI framework but in some areas it's quite weak...
So I was searching a lot to find a solution but finally I had to write my own stuff. It was taking
a lot of time to find out how to make this Windows taskbar feature possible in javaFX but I'm really happy because now I know, it was worth doing it.

And now I have good news: java 11 support is available!
Just remember to pass the necessary jvm argument `--add-exports javafx.graphics/com.sun.glass.ui=ALL-UNNAMED`  to the
java compiler.

The API is changed a little bit, all information is in the [README ](https://github.com/Dansoftowner/FXTaskbarProgressBar/blob/master/README.md) so please have a look at it :)!

If you have more issues don't hesitate to contact me!
I will keep this library up-to-date.

**Comment by JhonnySalles** [comment]
Thank you very much for all the work.

I already read your documentation, it is very explanatory. I will be checking the changes and implementing this version.

Really, JavaFx is a great update, and it is possible to create beautiful screens with its ease of adjustment and the implementation of styles.

He wins at several points, but sins at some. I believe that in the future, with several updates they can implement the missing features.

Your library really saved my life. I was ready to learn how to deal with bridj. But thanks to her I easily got what I wanted, which was to be able to see the status on the taskbar.

Thank you so much for all the work.
